# Name of your application. Used to uniquely configure containers.
service: blog

# Name of the container image.
image: dhruvcital/blog

builder:
  remote:
    arch: amd64

# Deploy to these servers.
servers:
  web:
    hosts:
      - 15.206.227.14

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: dhruvcital

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - RAILS_MASTER_KEY

# Use a different ssh user than root
ssh:
  user: ubuntu

volumes:
  - "storage:/rails/storage"
